sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t analallena/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true analallena/docker-react npm run test
